# Funding options for this project
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [ KevinTCoughlin ]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: platform/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# polar: username
# buy_me_a_coffee: username
# thanks_dev: username
# custom: ['https://example.com']

